### ISSUE TITLE
Federated recursive query

### ISSUE THREAD

**Issue by lavdim** [frmichel/sparql-micro-service#10] opened 2019-12-02 07:55 UTC
Hi,

I am trying to run the following query for combining data from a Jena Fuseki Endpoint with data from a SPARQL Endpoint created on top of a JSON Web Service, e.g.: 

http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key=[appKEY]&q=Berlin&format=json&date=25-11-2019&enddate=25-11-2019&tp=1

```
PREFIX ex:    <https://example.org/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
 
 SELECT * WHERE  {
             ?subj a ex:City;
                      rdfs:label ?cityName.
 
 SERVICE <http://endpoint1:3030/sparql-ms/worldweather/getWeatherByCity_sd/> {		
        SELECT * WHERE {  
                                           
            ?s ?p ?o;
                schema:name ?cityName;
                schema:startDate "2019-11-14";
                schema:endDate "2019-11-14";
                schema:hasReportHeader ?headerReport.
       }
 }}

```
Basically, the variable ?cityName is bound with a number of cities, therefore the query should be executed in an iterative way, i.e. for each value of the ?cityName variable there should be initiated a call to <http://endpoint1:3030/worldweather/getWeatherByCity_sd/>.

I have seen a possibility provided in the script manual_config_example/service.php to perform specific actions, but I am not sure how to make this in the best way.

Best,
Lavdim

**Comment by frmichel** [comment] 2019-12-03 14:25
Hi Lavdim,

I don't think that the manual config example will be helpful in this case.

Since the city name is a parameter of the SPARQL µs, it should be provided at each invocation. The problem is that we don't know the evaluation strategy of Fuseki: it may evaluate the first part, then evaluate the SERVICE clause by passing the values of ?cityName with a VALUES clause typically. But it may well invoke both parts independently and do the join at the end. In that case the SERVICE clause would have no values for ?cityName and the SPARQL µs invocation would fail.

There is no way to know it. You can try something, in case it would change Fuseki's evaluation strategy:
```sparql
SELECT * WHERE  {
?subj a ex:City;
   rdfs:label ?cityName.
 
  SERVICE <http://endpoint1:3030/sparql-ms/worldweather/getWeatherByCity_sd/> {		
        SELECT * WHERE {  
            ?s ?p ?o;
                schema:name ?cityName2;
                schema:startDate "2019-11-14";
                schema:endDate "2019-11-14";
                schema:hasReportHeader ?headerReport.
  }}
  FILTER (?cityName2 = ?cityName)
}
```

If this does not work, I'm afraid the only solution is to do 2 queries: first get the city names, and the inject the values into the SPARQL µs invocation.

Let me know.
   Franck.

**Comment by frmichel** [comment] 2019-12-06 10:35
Hi Lavdim,

I think I have a good lead for your. The problem is actually that ?cityName is not bound when Fuseki calls the SPARQL micro-service. That means we must force the evaluation of the variable before calling the service. One way of doing this is by binding it. Can you please try this solution:

```sparql
SELECT * WHERE  {
  ?subj a ex:City;
    rdfs:label ?cityName.

  BIND (?cityName as ?cityName2)
 
  SERVICE <http://endpoint1:3030/sparql-ms/worldweather/getWeatherByCity_sd/> {		
        SELECT * WHERE {  
            ?s ?p ?o;
                schema:name ?cityName2;
                schema:startDate "2019-11-14";
                schema:endDate "2019-11-14";
                schema:hasReportHeader ?headerReport.
  }}
}
```

Franck.

**Comment by lavdim** [comment] 2019-12-06 13:28
Hi Frank, 

thank you very much for your support. 

I also tried this way before, but unfortunately didn't work to me. Is this working to you, maybe I am doing something wrong? I tested it with Jena Fuseki and Stardog.

Lavdim

**Comment by frmichel** [comment] 2019-12-06 14:53
That works for me with the Corese-KRAM SPARQL engine. Not with Virtuoso, yet I think this is not because the service is invoked without values, but for some other reason.

What happens exactly with Fuseki and Stardog: do you see a trace saying that the input parameter was not provided with values?
If so, that means that Fuseki and Stardog do not optimize the query the way we would expect: since the BIND fixes the values of ?cityName2, then a basic optimization is to inject them into the SERVICE clause by rewriting the query, adding a VALUES or FILTER clause. 

Can you please check the SPARQL micro-service and send the SPARQL query that is actually received?

Franck.

**Comment by lavdim** [comment] 2019-12-06 15:35
I see. I tried now also with Corese-KRAM but this is the content in the log file:

``` [2019-12-06 16:22:49] NOTICE Context: --------- Starting SPARQL micro-service --------
[2019-12-06 16:22:49] NOTICE sparqlms\service: Query parameter (html special chars encoded) 'service': worldweather/getWeatherByCity_sd
[2019-12-06 16:22:49] NOTICE sparqlms\service: Query parameter (html special chars encoded) 'querymode': sparql
[2019-12-06 16:22:49] NOTICE Utils: Query HTTP header "Content-Type": application/x-www-form-urlencoded
[2019-12-06 16:22:49] NOTICE Utils: Query HTTP header "Accept": application/sparql-results+xml, application/rdf+xml
[2019-12-06 16:22:49] NOTICE sparqlms\service: Client SPARQL query (html special chars encoded):
prefix schema: &lt;http://schema.org/&gt;
prefix schemas: &lt;https://schema.org/&gt;
select ?s ?date ?sunrise ?sunset ?temp_maxC ?temp_minC ?time ?tempC ?windspeedKmph ?winddirDegree ?winddir16Point ?precipMM ?humidity ?visibility ?pressure
where {
  ?s ?p ?o .
  ?s schema:name ?cityName2 .
  ?s schema:startDate '2019-11-14' .
  ?s schema:endDate '2019-11-14' .
  ?s schema:hasReportHeader ?headerReport .
  ?headerReport schema:temp_maxCelsius ?temp_maxC .
  ?headerReport schema:temp_minCelsius ?temp_minC .
  ?headerReport schema:date ?date .
  ?headerReport schema:sunrise ?sunrise .
  ?headerReport schema:sunset ?sunset .
  ?headerReport schema:hourly ?hourly .
  ?hourly schema:time ?time .
  ?hourly schema:tempC ?tempC .
  ?hourly schema:windspeedKmph ?windspeedKmph .
  ?hourly schema:winddirDegree ?winddirDegree .
  ?hourly schema:winddir16Point ?winddir16Point .
  ?hourly schema:precipMM ?precipMM .
  ?hourly schema:humidity ?humidity .
  ?hourly schema:visibility ?visibility .
  ?hourly schema:pressure ?pressure .
}

[2019-12-06 16:22:59] ERROR sparqlms\service: exception 'EasyRdf_Exception' with message 'Request to sms-corese:8081 timed out' in /var/www/html/sparqlms-install/vendor/easyrdf/ea$
Stack trace:
#0 /var/www/html/sparqlms-install/vendor/easyrdf/easyrdf/lib/EasyRdf/Sparql/Client.php(284): EasyRdf_Http_Client->request()
#1 /var/www/html/sparqlms-install/vendor/easyrdf/easyrdf/lib/EasyRdf/Sparql/Client.php(194): EasyRdf_Sparql_Client->request('update', 'LOAD <http://lo...')
#2 /var/www/html/sparqlms-install/src/common/Utils.php(362): EasyRdf_Sparql_Client->update('LOAD <http://lo...')
#3 /var/www/html/sparqlms-install/src/common/Utils.php(412): frmichel\sparqlms\common\Utils::getServiceCustomArgsFromSparqlQuery('prefix schema: ...')
#4 /var/www/html/sparqlms-install/src/sparqlms/service.php(90): frmichel\sparqlms\common\Utils::getServiceCustomArgs()

```

Jena Fuseki returns the following message:

> Error 500: HTTP 400 error making the query: Bad Request

and the content of the log file is:
```
[2019-12-06 16:22:59] NOTICE sparqlms\service: Returning HTTP status 500.

[2019-12-06 16:22:59] NOTICE sparqlms\service: --------- Done - SPARQL   S execution --------
[2019-12-06 16:28:21] NOTICE Context: --------- Starting SPARQL micro-service --------
[2019-12-06 16:28:21] NOTICE sparqlms\service: Query parameter (html special chars encoded) 'service': worldweather/getWeatherByCity_sd
[2019-12-06 16:28:21] NOTICE sparqlms\service: Query parameter (html special chars encoded) 'querymode': sparql
[2019-12-06 16:28:21] NOTICE Utils: Query HTTP header "Content-Type" undefined.
[2019-12-06 16:28:21] NOTICE Utils: Query HTTP header "Accept": application/sparql-results+xml
[2019-12-06 16:28:21] NOTICE sparqlms\service: Client SPARQL query (html special chars encoded):
SELECT  ?s ?date ?sunrise ?sunset ?temp_maxC ?temp_minC ?time ?tempC ?windspeedKmph ?winddirDegree ?winddir16Point ?precipMM ?humidity ?visibility ?pressure
WHERE
  { ?s        ?p                    ?o ;
              &lt;http://schema.org/name&gt;  ?cityName2 ;
              &lt;http://schema.org/startDate&gt;  &quot;2019-11-14&quot; ;
              &lt;http://schema.org/endDate&gt;  &quot;2019-11-14&quot; ;
              &lt;http://schema.org/hasReportHeader&gt;  ?headerReport .
    ?headerReport
              &lt;http://schema.org/temp_maxCelsius&gt;  ?temp_maxC ;
              &lt;http://schema.org/temp_minCelsius&gt;  ?temp_minC ;
              &lt;http://schema.org/date&gt;  ?date ;
              &lt;http://schema.org/sunrise&gt;  ?sunrise ;
              &lt;http://schema.org/sunset&gt;  ?sunset ;
              &lt;http://schema.org/hourly&gt;  ?hourly .
    ?hourly   &lt;http://schema.org/time&gt;  ?time ;
              &lt;http://schema.org/tempC&gt;  ?tempC ;
              &lt;http://schema.org/windspeedKmph&gt;  ?windspeedKmph ;
              &lt;http://schema.org/winddirDegree&gt;  ?winddirDegree ;
              &lt;http://schema.org/winddir16Point&gt;  ?winddir16Point ;
              &lt;http://schema.org/precipMM&gt;  ?precipMM ;
              &lt;http://schema.org/humidity&gt;  ?humidity ;
              &lt;http://schema.org/visibility&gt;  ?visibility ;
              &lt;http://schema.org/pressure&gt;  ?pressure
  }

[2019-12-06 16:28:21] WARNING Utils: No triple patterns with predicate "http://schema.org/name" (for service argument "city")
[2019-12-06 16:28:21] NOTICE Utils: --------- Done - SPARQL   S execution --------

```

so, as you explained, it is related with binding values and query decomposition and execution order.

**Comment by frmichel** [comment] 2019-12-06 16:47
About the try with Corese, it seems that the Corese service is not reachable: Request to sms-corese:8081 timed out
Check property sparql_endpoint  in your config.ini file.
But even though, there is no VALUES or FILTER clause in the SPARQL query, so it will fail anyway, just like the one submitted through Fuseki. Hence the result error: 

    No triple patterns with predicate "http://schema.org/name" (for service argument "city")

Can you please send me the complete query that you submit? I wonder why the bind does not change anything.

**Comment by lavdim** [comment] 2019-12-09 08:06
Sure, here is the entire query:

```
prefix schema: <http://schema.org/>
prefix vmo:   <http://example/> 
                                                   
 SELECT distinct * WHERE {    

  ?s1 vmo:cityName ?cityName.   

   BIND (?cityName as ?cityName2)
      
       SERVICE <http://endpoint1:3030/sparql-ms/worldweather/getWeatherByCity_sd/>{
           SELECT ?s ?date ?sunrise ?sunset ?temp_maxC ?temp_minC ?time ?tempC ?windspeedKmph ?winddirDegree ?winddir16Point 
           ?precipMM ?humidity ?visibility ?pressure WHERE {                              
            ?s ?p ?o;
                schema:name ?cityName2;
                schema:startDate "2019-11-14";
                schema:endDate "2019-11-14";
                schema:hasReportHeader ?headerReport.

             ?headerReport schema:temp_maxCelsius ?temp_maxC;
              schema:temp_minCelsius ?temp_minC;
              schema:date ?date;
              schema:sunrise ?sunrise;
              schema:sunset ?sunset;
              schema:hourly ?hourly;
           . 
             ?hourly schema:time ?time;
                     schema:tempC ?tempC;
                     schema:windspeedKmph ?windspeedKmph;
             schema:winddirDegree  ?winddirDegree;
             schema:winddir16Point ?winddir16Point;
             schema:precipMM ?precipMM;
             schema:humidity ?humidity;
             schema:visibility ?visibility;
             schema:pressure ?pressure;
            .

        }}
        

 } ORDER BY ?date
```

and here are example triples with cityNames:

```
vmo:Berlin  vmo:cityName  "Berlin" .
vmo:Paris  vmo:cityName  "Paris" .
vmo:London  vmo:cityName  "London" .

```

these are the values in config.ini: 

```
# --- Write-enabled SPARQL endpoint to store the temporary graphs. Mandatory
sparql_endpoint = http://sms-corese:8081/sparql

# --- SPARQL-to-SPIN translation service. Optional
spin_endpoint = http://sms-corese:8081/service/sparql-to-spin

```

so, basically it is working fine, if I only send:

```
prefix schema: <http://schema.org/>
prefix vmo:   <http://example/> 
                                                   
 SELECT distinct * WHERE {    
      
       SERVICE <http://endpoint1:3030/sparql-ms/worldweather/getWeatherByCity_sd/>{
           SELECT ?s ?date ?sunrise ?sunset ?temp_maxC ?temp_minC ?time ?tempC ?windspeedKmph ?winddirDegree ?winddir16Point 
           ?precipMM ?humidity ?visibility ?pressure WHERE {                              
            ?s ?p ?o;
                schema:name "Berlin";
                schema:startDate "2019-11-14";
                schema:endDate "2019-11-14";
                schema:hasReportHeader ?headerReport.

             ?headerReport schema:temp_maxCelsius ?temp_maxC;
              schema:temp_minCelsius ?temp_minC;
              schema:date ?date;
              schema:sunrise ?sunrise;
              schema:sunset ?sunset;
              schema:hourly ?hourly;
           . 
             ?hourly schema:time ?time;
                     schema:tempC ?tempC;
                     schema:windspeedKmph ?windspeedKmph;
             schema:winddirDegree  ?winddirDegree;
             schema:winddir16Point ?winddir16Point;
             schema:precipMM ?precipMM;
             schema:humidity ?humidity;
             schema:visibility ?visibility;
             schema:pressure ?pressure;
            .

        }}
        

 } ORDER BY ?date

```

**Comment by frmichel** [comment] 2019-12-10 09:17
Hi Latvim,

I just discussed with the developer of Corese who gave me the answer. This is a sublte question of SPARQL semantics.

The pb is that ?cityName2 is not projected by the SELECT within the SERVICE clause: there is not SELECT ?cityName2 ?s ?date...

Since it is not projected, then, according the semantics of SPARQL, variable ?cityName2 within the SERVICE clause and variable ?cityName2 outside, are **NOT** one and the same.

So basically simply add ?cityName2 in the select:
```sparql
       SERVICE <http://endpoint1:3030/sparql-ms/worldweather/getWeatherByCity_sd/>{
           SELECT ?cityName2 ?s ?date ?sunrise ?sunset ?temp_maxC ?temp_minC ?time ?tempC ?windspeedKmph ?winddirDegree ?winddir16Point 
           ?precipMM ?humidity ?visibility ?pressure WHERE {                              
            ?s ?p ?o;
                schema:name ?cityName2;
                ...
```
You may even not need to add ?cityName2, just ?cityName would probably work.

Let me know.

**Comment by lavdim** [comment] 2019-12-11 07:32
Hi Frank, 

thanks a lot for your support. I agree with the developer of Corese about the SPARQL semantics.

By adding the variable ?cityName2 to the SELECT within SERVICE clause as you already described, it seems to be working fine with Jena Fuseki, here is the content within LOG file:

```
[2019-12-10 10:46:22] NOTICE Context: --------- Starting SPARQL micro-service --------
[2019-12-10 10:46:22] NOTICE sparqlms\service: Query parameter (html special chars encoded) 'service': worldweather/getWeatherByCity_sd
[2019-12-10 10:46:22] NOTICE sparqlms\service: Query parameter (html special chars encoded) 'querymode': sparql
[2019-12-10 10:46:22] NOTICE Utils: Query HTTP header "Content-Type" undefined.
[2019-12-10 10:46:22] NOTICE Utils: Query HTTP header "Accept": application/sparql-results+xml
[2019-12-10 10:46:22] NOTICE sparqlms\service: Client SPARQL query (html special chars encoded):
SELECT  ?cityName2 ?s ?date ?sunrise ?sunset ?temp_maxC ?temp_minC ?time ?tempC ?windspeedKmph ?winddirDegree ?winddir16Point ?precipMM ?humidity ?visibility ?pressure
WHERE
  { ?s        ?p                    ?o ;
              &lt;http://schema.org/name&gt;  &quot;Stuttgart&quot; ;
              &lt;http://schema.org/startDate&gt;  &quot;2019-11-14&quot; ;
              &lt;http://schema.org/endDate&gt;  &quot;2019-11-14&quot; ;
              &lt;http://schema.org/hasReportHeader&gt;  ?headerReport .
    ?headerReport
              &lt;http://schema.org/temp_maxCelsius&gt;  ?temp_maxC ;
              &lt;http://schema.org/temp_minCelsius&gt;  ?temp_minC ;
              &lt;http://schema.org/date&gt;  ?date ;
              &lt;http://schema.org/sunrise&gt;  ?sunrise ;
              &lt;http://schema.org/sunset&gt;  ?sunset ;
              &lt;http://schema.org/hourly&gt;  ?hourly .
    ?hourly   &lt;http://schema.org/time&gt;  ?time ;
              &lt;http://schema.org/tempC&gt;  ?tempC ;
              &lt;http://schema.org/windspeedKmph&gt;  ?windspeedKmph ;
              &lt;http://schema.org/winddirDegree&gt;  ?winddirDegree ;
              &lt;http://schema.org/winddir16Point&gt;  ?winddir16Point ;
              &lt;http://schema.org/precipMM&gt;  ?precipMM ;
              &lt;http://schema.org/humidity&gt;  ?humidity ;
              &lt;http://schema.org/visibility&gt;  ?visibility ;
              &lt;http://schema.org/pressure&gt;  ?pressure
  }

[2019-12-10 10:46:23] NOTICE sparqlms\service: Read service custom arguments: Array
(
    [city] => Array
        (
            [0] => Berlin
        )

    [startDateP] => Array
        (
            [0] => 2019-11-14
        )

    [enddateP] => Array
        (
            [0] => 2019-11-14
        )

)


[2019-12-10 10:46:23] NOTICE sparqlms\service: --------- Done - SPARQL   S execution --------
[2019-12-10 10:46:23] NOTICE Context: --------- Starting SPARQL micro-service --------
[2019-12-10 10:46:23] NOTICE sparqlms\service: Query parameter (html special chars encoded) 'service': worldweather/getWeatherByCity_sd
[2019-12-10 10:46:23] NOTICE sparqlms\service: Query parameter (html special chars encoded) 'querymode': sparql
[2019-12-10 10:46:23] NOTICE Utils: Query HTTP header "Content-Type" undefined.
[2019-12-10 10:46:23] NOTICE Utils: Query HTTP header "Accept": application/sparql-results+xml
[2019-12-10 10:46:23] NOTICE sparqlms\service: Client SPARQL query (html special chars encoded):
SELECT  ?cityName2 ?s ?date ?sunrise ?sunset ?temp_maxC ?temp_minC ?time ?tempC ?windspeedKmph ?winddirDegree ?winddir16Point ?precipMM ?humidity ?visibility ?pressure
WHERE
  { ?s        ?p                    ?o ;
              &lt;http://schema.org/name&gt;  &quot;Bonn&quot; ;
              &lt;http://schema.org/startDate&gt;  &quot;2019-11-14&quot; ;
              &lt;http://schema.org/endDate&gt;  &quot;2019-11-14&quot; ;
              &lt;http://schema.org/hasReportHeader&gt;  ?headerReport .
    ?headerReport
              &lt;http://schema.org/temp_maxCelsius&gt;  ?temp_maxC ;
              &lt;http://schema.org/temp_minCelsius&gt;  ?temp_minC ;
              &lt;http://schema.org/date&gt;  ?date ;
              &lt;http://schema.org/sunrise&gt;  ?sunrise ;
              &lt;http://schema.org/sunset&gt;  ?sunset ;
              &lt;http://schema.org/hourly&gt;  ?hourly .
    ?hourly   &lt;http://schema.org/time&gt;  ?time ;
              &lt;http://schema.org/tempC&gt;  ?tempC ;
              &lt;http://schema.org/windspeedKmph&gt;  ?windspeedKmph ;
              &lt;http://schema.org/winddirDegree&gt;  ?winddirDegree ;
              &lt;http://schema.org/winddir16Point&gt;  ?winddir16Point ;
              &lt;http://schema.org/precipMM&gt;  ?precipMM ;
              &lt;http://schema.org/humidity&gt;  ?humidity ;
              &lt;http://schema.org/visibility&gt;  ?visibility ;
              &lt;http://schema.org/pressure&gt;  ?pressure
  }

[2019-12-10 10:46:23] NOTICE sparqlms\service: Read service custom arguments: Array
(
    [city] => Array
        (
            [0] => Paris
        )

    [startDateP] => Array
        (
            [0] => 2019-11-14
        )

    [enddateP] => Array
        (
            [0] => 2019-11-14
        )

)

```

but in Corese, this doesn't seem to be working, here is the LOG file after executing through Corese:

```

[2019-12-10 10:43:37] NOTICE Context: --------- Starting SPARQL micro-service --------
[2019-12-10 10:43:37] NOTICE sparqlms\service: Query parameter (html special chars encoded) 'service': worldweather/getWeatherByCity_sd
[2019-12-10 10:43:37] NOTICE sparqlms\service: Query parameter (html special chars encoded) 'querymode': sparql
[2019-12-10 10:43:37] NOTICE Utils: Query HTTP header "Content-Type": application/x-www-form-urlencoded
[2019-12-10 10:43:37] NOTICE Utils: Query HTTP header "Accept": application/sparql-results+xml, application/rdf+xml
[2019-12-10 10:43:37] NOTICE sparqlms\service: Client SPARQL query (html special chars encoded):
prefix schema: &lt;http://schema.org/&gt;
prefix schemas: &lt;https://schema.org/&gt;
select ?cityName2 ?s ?date ?sunrise ?sunset ?temp_maxC ?temp_minC ?time ?tempC ?windspeedKmph ?winddirDegree ?winddir16Point ?precipMM ?humidity ?visibility ?pressure
where {
  ?s ?p ?o .
  ?s schema:name ?cityName2 .
  ?s schema:startDate '2019-11-14' .
  ?s schema:endDate '2019-11-14' .
  ?s schema:hasReportHeader ?headerReport .
  ?headerReport schema:temp_maxCelsius ?temp_maxC .
  ?headerReport schema:temp_minCelsius ?temp_minC .
  ?headerReport schema:date ?date .
  ?headerReport schema:sunrise ?sunrise .
  ?headerReport schema:sunset ?sunset .
  ?headerReport schema:hourly ?hourly .
  ?hourly schema:time ?time .
  ?hourly schema:tempC ?tempC .
  ?hourly schema:windspeedKmph ?windspeedKmph .
  ?hourly schema:winddirDegree ?winddirDegree .
  ?hourly schema:winddir16Point ?winddir16Point .
  ?hourly schema:precipMM ?precipMM .
  ?hourly schema:humidity ?humidity .
  ?hourly schema:visibility ?visibility .
  ?hourly schema:pressure ?pressure .
  filter ((?cityName2 = 'Berlin') || (?cityName2 = 'Paris'))
}

[2019-12-10 10:43:47] ERROR sparqlms\service: exception 'EasyRdf_Exception' with message 'Request to sms-corese:8081 timed out' in /var/www/html/sparqlms-install/vendor/easyrdf/ea$
Stack trace:
#0 /var/www/html/sparqlms-install/vendor/easyrdf/easyrdf/lib/EasyRdf/Sparql/Client.php(284): EasyRdf_Http_Client->request()
#1 /var/www/html/sparqlms-install/vendor/easyrdf/easyrdf/lib/EasyRdf/Sparql/Client.php(194): EasyRdf_Sparql_Client->request('update', 'LOAD <http://sm...')
#2 /var/www/html/sparqlms-install/src/common/Utils.php(362): EasyRdf_Sparql_Client->update('LOAD <http://sm...')
#3 /var/www/html/sparqlms-install/src/common/Utils.php(412): frmichel\sparqlms\common\Utils::getServiceCustomArgsFromSparqlQuery('prefix schema: ...')

```

Actually, I thing the clause with  ` filter ((?cityName2 = 'Berlin') || (?cityName2 = 'Paris')) ` shouldn't work in principle, since it assumes that the above part of the query has access to the entire dataset, and then the filtering is done later on specific cities, which is not the case here, since the WEB API Service excepts city as a parameter in order to be able to return values for that particular city.

**Comment by frmichel** [comment] 2019-12-11 09:51
Hi Lavdim,

So first thing, great that it works with Fuseki.

With Corese, there is a first technical problem: 'Request to sms-corese:8081 timed out' means that you can't reach Corese. Can you make sure that the Corese container is properly started and that the ports configuration is consistent on both sides?

Now, you point to a bug I had not foreseen:
- Fuseki rewrites the query by replacing the ?cityName2 variable with its values, this results in one invocation for each city value.
- Corese rewrites the query by passing the values as a filter (val1 or val2). 

Semantically, both rewritings are equivalent: they should produce the same solution sets.

But I just looked into the code: when the SPARQL µs gets multiple values for an argument, it passes them all at once to the Web API as a comma-separated list, hence it's going to call the API with: ...&cityName=Berlin,Stutgart,Bon&...

I made this for a use case with tags in the Flickr API, which was ok. But for your use case, indeed this is wrong. Instead, there should be one call to the Web API for each value.

There is some development involved here, I can't tell you when this is gonna be ready. But in the meantime, I can propose a workaround: instead of using the Service Description configuration, use the config.ini => the arguments will be passed on the URL of the SPARQL µs, like  

    SERVICE <http://endpoint1:3030/sparql-ms/worldweather/getWeatherByCity?startDate=2019-11-14&endDate=2019-11-14&cityName=Berlin>

To invoke it, you will have to build the URL:

    bind( concat('http://endpoint1:3030/sparql-ms/worldweather/getWeatherByCity?startDate=2019-11-14&endDate=2019-11-14&cityName=', ?cityName) as ?serviceUrl )
    SERVICE ?serviceUrl { ... }

Here, you are sure that the values will be passed properly one by one, and you will get the right solutions.

Is that ok with you?

Franck.

**Comment by lavdim** [comment] 2019-12-12 08:53
Hi Franck,

yes, that is great, at least for demo purposes. 

Regarding: 'Request to sms-corese:8081 timed out' , I guess this might be happening because of the SPARQL rewritings because I am able to do other queries with Corese, and also from JENA Fuseki it is working fine.

> ...&cityName=Berlin,Stutgart,Bon&... => Right, I also have seen that. As you said, this is appropriate for specific use cases when the Web API accepts as a parameter a range of values, but unfortunately not in our case. 

Good idea for using config.ini and concatenating the values within Service URL. I will try that at some point if Jena Fuseki doesn't meet the requirements.

Again, thank you very much for your support.
 
Best,
Lavdim

**Comment by frmichel** [comment] 2019-12-12 13:25
> Regarding: 'Request to sms-corese:8081 timed out' , I guess this might be happening because of the SPARQL rewritings because I am able to do other queries with Corese, and also from JENA Fuseki it is working fine.

Well this is really weird. This happens when we load the SPARQL query translated into SPIN as as new temporary named graph. To me, it sounds like a problem of docker image deployment.

Can you have a look at the logs directory? There should be a log file generated by the Corese image: kgram_server.log. Can you see if there is anything in here: does it start? Is there an error?
Also, can you turn the SPARQL micro-services log level to DEBUG in the main config.ini file, and rerun. Then maybe you can attach the log file to the issue.

> Again, thank you very much for your support.
No problem, you help me improve the software!

**Comment by frmichel** [comment] 2020-01-23 10:44
Hi Lavdim,

I've just committed a new version [0.4.3_RC](https://github.com/frmichel/sparql-micro-service/tree/0.4.3_RC) that you would like to try.

The change is about the way a SPARQL micro-service deals with the values it receives for one argument: so far, the values were passed to the Web API as a comma-separated list of values.
Now you have another possible strategy: invoke the Web API once for each of these values.
The result of the multiple invocations are all stored in the same graph, then the SPARQL query is evaluated.

Check the [configuration doc](https://github.com/frmichel/sparql-micro-service/blob/0.4.3_RC/doc/02-config.md). You can either use 
- the `custom_parameter.pass_multiple_values_as_csv` in the config.ini config, or
- property `sms:passMultipleValuesAsCsv` in the Service Description config

Let me know if you need some help upgrading.

Franck.

**Closed** 2021-02-22 11:50 UTC
